# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ new-gtfs-sources ]
  pull_request:
    branches: [ new-gtfs-sources ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set up Get All Changed Files action
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: Verify source url
        run: |
          # stop the build if the source url submitted already exists on the database
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            python ./scripts/verify_source_url.py -f "$changed_file"
          done
